version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - MONGO_URI=${MONGO_URI}
    volumes:
      - app-data:/app/data
volumes:
  app-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/ebs-data